### ISSUE TITLE
Fix storybook

### ISSUE THREAD

**Issue by dvdanielamoitzi** [datavisyn/tdp_core#809]
### Environment

 * Release number or git hash: develop
 * Deployed / Local: local
---

### Steps to reproduce the bug

1. yarn run storybook / yarn run storybook:build

### Observed Behavior
When running the above command, we get the following error:

`ERR! TypeError: Cannot read properties of undefined (reading 'data')
ERR!     at setData (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:84:15)
ERR!     at CachedInputFileSystem.finalInputFileSystem._writeVirtualFile (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:118:9)
ERR!     at VirtualModulesPlugin.writeModule (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:64:24)
ERR!     at /home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:165:14
ERR!     at Array.forEach (<anonymous>)
ERR!     at afterResolversHook (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:164:40)
ERR!     at Hook.eval [as call] (eval at create (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
ERR!     at Hook.CALL_DELEGATE [as _call] (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/tapable/lib/Hook.js:14:14)
ERR!     at WebpackOptionsApply.process (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack/lib/WebpackOptionsApply.js:695:33)
ERR!     at createCompiler (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack/lib/webpack.js:80:28)
ERR!  TypeError: Cannot read properties of undefined (reading 'data')
ERR!     at setData (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:84:15)
ERR!     at CachedInputFileSystem.finalInputFileSystem._writeVirtualFile (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:118:9)
ERR!     at VirtualModulesPlugin.writeModule (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:64:24)
ERR!     at /home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:165:14
ERR!     at Array.forEach (<anonymous>)
ERR!     at afterResolversHook (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack-virtual-modules/index.js:164:40)
ERR!     at Hook.eval [as call] (eval at create (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
ERR!     at Hook.CALL_DELEGATE [as _call] (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/tapable/lib/Hook.js:14:14)
ERR!     at WebpackOptionsApply.process (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack/lib/WebpackOptionsApply.js:695:33)
ERR!     at createCompiler (/home/daniela/Workspaces/standalone_repos/tdp_core/node_modules/webpack/lib/webpack.js:80:28)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.`

Thanks for taking the time to fill out this bug report 🤗
Make sure there aren't any open/closed issues for this topic 😃

**Comment by dvdanielamoitzi** [comment]
- [ ] [updating to webpack 5](https://storybook.js.org/docs/react/get-started/install)
- [ ] [use our custom webpack config](https://storybook.js.org/docs/react/builders/webpack#using-your-existing-config)
      just like we do with [cypress](https://github.com/datavisyn/visyn_scripts/blob/develop/tests_fixtures/standalone_template/cypress.config.ts#L17)
