### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by lehnerchristian** [datavisyn/tdp_core#93]
* Release number or git hash: 
* Web browser version and OS: 
* Environment (local or deployed): deployed dev version

### Steps to reproduce

1. open dtiles-dev.app.datavisyn.io
2. search a gene or cell line

### Observed behavior
* internal server error

```
08:55:47 INFO tdp_core.db: creating session
08:55:47 INFO tdp_core.db: SELECT celllinename as id, celllinename AS text FROM cellline.tdp_cellline WHERE LOWER(celllinename) LIKE :query AND species = :species ORDER BY celllinename ASC LIMIT 11 OFFSET 0
08:55:47 INFO tdp_core.db: creating session
08:55:47 INFO tdp_core.db: SELECT ensg as id, symbol AS text FROM public.tdp_gene WHERE (LOWER(symbol) LIKE :query OR LOWER(ensg) LIKE :query) AND species = :species ORDER BY symbol ASC LIMIT 11 OFFSET 0
08:55:47 INFO tdp_core.db: creating session
08:55:47 INFO tdp_core.db: SELECT tissuename as id, tissuename AS text FROM tissue.tdp_tissue WHERE LOWER(tissuename) LIKE :query AND species = :species ORDER BY tissuename ASC LIMIT 11 OFFSET 0
08:55:47 INFO tdp_core.db: removing session again
08:55:47 INFO tdp_core.db: removing session again
08:55:47 INFO tdp_core.db: removing session again
08:55:49 INFO tdp_core.db: creating session
08:55:49 INFO tdp_core.db: SELECT celllinename as id, celllinename AS text FROM cellline.tdp_cellline WHERE LOWER(celllinename) LIKE :query AND species = :species ORDER BY celllinename ASC LIMIT 11 OFFSET 0
08:55:49 INFO tdp_core.db: creating session
08:55:49 INFO tdp_core.db: SELECT ensg as id, symbol AS text FROM public.tdp_gene WHERE (LOWER(symbol) LIKE :query OR LOWER(ensg) LIKE :query) AND species = :species ORDER BY symbol ASC LIMIT 11 OFFSET 0
08:55:49 INFO tdp_core.db: creating session
08:55:49 INFO tdp_core.db: SELECT tissuename as id, tissuename AS text FROM tissue.tdp_tissue WHERE LOWER(tissuename) LIKE :query AND species = :species ORDER BY tissuename ASC LIMIT 11 OFFSET 0
08:55:49 INFO tdp_core.db: removing session again
08:55:49 INFO tdp_core.db: removing session again
08:55:49 INFO tdp_core.db: removing session again
08:55:49 INFO tdp_core.db: creating session
08:55:49 INFO tdp_core.db: SELECT celllinename as id, celllinename AS text FROM cellline.tdp_cellline WHERE LOWER(celllinename) LIKE :query AND species = :species ORDER BY celllinename ASC LIMIT 11 OFFSET 0
08:55:49 INFO tdp_core.db: removing session again
08:55:49 INFO tdp_core.db: creating session
08:55:49 INFO tdp_core.db: SELECT ensg as id, symbol AS text FROM public.tdp_gene WHERE (LOWER(symbol) LIKE :query OR LOWER(ensg) LIKE :query) AND species = :species ORDER BY symbol ASC LIMIT 11 OFFSET 0
08:55:49 INFO tdp_core.db: creating session
08:55:49 INFO tdp_core.db: SELECT tissuename as id, tissuename AS text FROM tissue.tdp_tissue WHERE LOWER(tissuename) LIKE :query AND species = :species ORDER BY tissuename ASC LIMIT 11 OFFSET 0
08:55:50 INFO tdp_core.db: removing session again
08:55:50 INFO tdp_core.db: removing session again
08:55:51 INFO tdp_core.db: creating session
08:55:51 INFO tdp_core.db: set statement_timeout to '5min'
08:55:51 INFO tdp_core.db: set statement_timeout to '5min'
08:55:51 INFO tdp_core.db: SELECT symbol as id, * FROM public.tdp_gene WHERE ensg = :ensg
08:55:51 INFO tdp_core.db: removing session again
08:55:51 ERROR tdp_core.sql: Exception on /publicdb/gene_all_columns/filter [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
return func(*args, **kwargs)
File "/phovea/tdp_core/sql.py", line 89, in get_filtered_data
r, view = db.get_filtered_data(database, view_name, request.args)
File "/phovea/tdp_core/db.py", line 304, in get_filtered_data
return get_data(database, view_name, replacements, processed_args, extra_args, where_clause)
File "/phovea/tdp_core/db.py", line 276, in get_data
r = sess.run(query.format(**replace), **kwargs)
File "/phovea/tdp_core/db.py", line 104, in run
result = self._session.execute(parsed, kwargs)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1139, in execute
bind, close_with_result=True).execute(clause, params or
{}
)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
compiled_sql, distilled_params
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
exc_info
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: text = text[]
LINE 1: ...mbol as id, * FROM public.tdp_gene WHERE ensg = ARRAY['E...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
[SQL: ' SELECT symbol as id, * FROM public.tdp_gene WHERE ensg = %(ensg)s'] [parameters: {'ensg': [u'ENSG00000146648']}]
[2018-03-09 08:55:51,628] ERROR in app: Exception on /publicdb/gene_all_columns/filter [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
return func(*args, **kwargs)
File "/phovea/tdp_core/sql.py", line 89, in get_filtered_data
r, view = db.get_filtered_data(database, view_name, request.args)
File "/phovea/tdp_core/db.py", line 304, in get_filtered_data
return get_data(database, view_name, replacements, processed_args, extra_args, where_clause)
File "/phovea/tdp_core/db.py", line 276, in get_data
r = sess.run(query.format(**replace), **kwargs)
File "/phovea/tdp_core/db.py", line 104, in run
result = self._session.execute(parsed, kwargs)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1139, in execute
bind, close_with_result=True).execute(clause, params or
{}
)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
compiled_sql, distilled_params
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
exc_info
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: text = text[]
LINE 1: ...mbol as id, * FROM public.tdp_gene WHERE ensg = ARRAY['E...
^
HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.
[SQL: ' SELECT symbol as id, * FROM public.tdp_gene WHERE ensg = %(ensg)s'] [parameters: {'ensg': [u'ENSG00000146648']}]
```

### Expected behavior
* no internal server error

**Comment by mstreit** [comment]
I still get an Internal Server Error when adding the second gene in the deployed version. Or is this issue also already solved?

**Comment by lehnerchristian** [comment]
That's another one:
```
12:24:29 INFO tdp_core.db: creating session
12:24:29 INFO tdp_core.db: set statement_timeout to '5min'
12:24:29 INFO tdp_core.db: set statement_timeout to '5min'
12:24:29 INFO tdp_core.db: SELECT symbol as id, * FROM public.tdp_gene WHERE ensg IN :ensg
12:24:29 INFO tdp_core.db: removing session again
12:24:29 ERROR tdp_core.sql: Exception on /publicdb/gene_all_columns/filter [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
return func(*args, **kwargs)
File "/phovea/tdp_core/sql.py", line 89, in get_filtered_data
r, view = db.get_filtered_data(database, view_name, request.args)
File "/phovea/tdp_core/db.py", line 304, in get_filtered_data
return get_data(database, view_name, replacements, processed_args, extra_args, where_clause)
File "/phovea/tdp_core/db.py", line 276, in get_data
r = sess.run(query.format(**replace), **kwargs)
File "/phovea/tdp_core/db.py", line 104, in run
result = self._session.execute(parsed, kwargs)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1139, in execute
bind, close_with_result=True).execute(clause, params or
{}
)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
compiled_sql, distilled_params
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
exc_info
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near "ARRAY"
LINE 1: ...l as id, * FROM public.tdp_gene WHERE ensg IN ARRAY['ENS...
^
[SQL: ' SELECT symbol as id, * FROM public.tdp_gene WHERE ensg IN %(ensg)s'] [parameters: {'ensg': [u'ENSG00000120738', u'ENSG00000166535']}]
[2018-03-09 12:24:29,783] ERROR in app: Exception on /publicdb/gene_all_columns/filter [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
return func(*args, **kwargs)
File "/phovea/tdp_core/sql.py", line 89, in get_filtered_data
r, view = db.get_filtered_data(database, view_name, request.args)
File "/phovea/tdp_core/db.py", line 304, in get_filtered_data
return get_data(database, view_name, replacements, processed_args, extra_args, where_clause)
File "/phovea/tdp_core/db.py", line 276, in get_data
r = sess.run(query.format(**replace), **kwargs)
File "/phovea/tdp_core/db.py", line 104, in run
result = self._session.execute(parsed, kwargs)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1139, in execute
bind, close_with_result=True).execute(clause, params or
{}
)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
return meth(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
compiled_sql, distilled_params
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
exc_info
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
context)
File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
cursor.execute(statement, parameters)
ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near "ARRAY"
LINE 1: ...l as id, * FROM public.tdp_gene WHERE ensg IN ARRAY['ENS...
^
[SQL: ' SELECT symbol as id, * FROM public.tdp_gene WHERE ensg IN %(ensg)s'] [parameters: {'ensg': [u'ENSG00000120738', u'ENSG00000166535']}]
```
